# Generated by Django 2.1.7 on 2019-08-09 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifttt', '0002_auto_20190809_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifttt.Clause'),
        ),
    ]
