# Generated by Django 2.1.7 on 2019-08-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifttt', '0003_event_clause'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='last_true',
            field=models.BooleanField(default=False),
        ),
    ]
