# Generated by Django 2.1.7 on 2019-08-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifttt', '0004_clause_last_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_code', models.CharField(blank=True, max_length=5000, null=True)),
                ('trigger_identity', models.CharField(blank=True, max_length=5000, null=True)),
                ('clause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ifttt.Clause')),
            ],
        ),
    ]
