# Generated by Django 2.1.7 on 2019-08-10 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifttt', '0005_triggers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Triggers',
            new_name='Trigger',
        ),
    ]
